

USE refconnect;

INSERT INTO skills (skill_name) VALUES
('JavaScript'),
('Python'),
('Java'),
('React'),
('Node.js'),
('SQL'),
('HTML/CSS'),
('TypeScript'),
('AWS'),
('Docker'),
('MongoDB'),
('Git'),
('Machine Learning'),
('Data Analysis'),
('REST APIs'),
('C++'),
('Kubernetes'),
('Flutter'),
('Go'),
('Figma');

-- ============================================
-- 2. Users (10 demo users across all roles)
-- Passwords are all "demo1234" hashed with bcrypt (10 rounds)
-- Hash: $2a$10$rQnM1kJ3F5g4y5N7s8vZXe6xW2p0q1m4k3j5h7g9f8d6s4a2z0x1y
-- NOTE: The actual hash will be generated by the app during registration.
-- For seeding, we use a pre-computed bcrypt hash of "demo1234"
-- ============================================
-- Using bcrypt hash of "demo1234":
-- $2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi

INSERT INTO users (name, email, password, role) VALUES
('Aarav Sharma',     'student@demo.com',      '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'student'),
('Priya Patel',      'student2@demo.com',     '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'student'),
('Rahul Verma',      'alumni@demo.com',       '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'alumni'),
('Sneha Gupta',      'alumni2@demo.com',      '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'alumni'),
('Vikram Singh',     'employee@demo.com',     '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'employee'),
('Ananya Reddy',     'employee2@demo.com',    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'employee'),
('Kiran Desai',      'recruiter@demo.com',    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'recruiter'),
('Meera Joshi',      'recruiter2@demo.com',   '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'recruiter'),
('Arjun Nair',       'employee3@demo.com',    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'employee'),
('Divya Krishnan',   'student3@demo.com',     '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'student');

-- ============================================
-- 3. Profiles
-- ============================================
INSERT INTO profiles (user_id, bio, education, experience, resume_link, linkedin, github, location) VALUES
(1,  'Passionate CS student looking for SDE internships.',           'B.Tech CSE, IIT Delhi (2024)',            NULL,                                            'https://resume.io/aarav',     'https://linkedin.com/in/aarav',     'https://github.com/aarav',     'New Delhi'),
(2,  'Final year student interested in data science and ML.',        'B.Tech AI/ML, BITS Pilani (2024)',        'Intern at DataCorp (Summer 2023)',               'https://resume.io/priya',     'https://linkedin.com/in/priya',     'https://github.com/priya',     'Hyderabad'),
(3,  'Software Engineer with 3 years of experience.',               'B.Tech CSE, NIT Trichy (2021)',           '3 years at Infosys as Full Stack Developer',    'https://resume.io/rahul',     'https://linkedin.com/in/rahul',     'https://github.com/rahul',     'Bangalore'),
(4,  'Product Manager turned mentor, love helping students.',        'MBA, IIM Ahmedabad (2020)',               '5 years at Flipkart, now at Google',            'https://resume.io/sneha',     'https://linkedin.com/in/sneha',     NULL,                            'Mumbai'),
(5,  'Senior SDE at Google, happy to refer talented candidates.',    'B.Tech CSE, IIT Bombay (2019)',           '5 years at Google, Cloud Platform team',        'https://resume.io/vikram',    'https://linkedin.com/in/vikram',    'https://github.com/vikram',    'Bangalore'),
(6,  'Backend engineer at Microsoft, passionate about mentoring.',   'M.Tech CSE, IISC Bangalore (2020)',       '4 years at Microsoft, Azure team',              'https://resume.io/ananya',    'https://linkedin.com/in/ananya',    'https://github.com/ananya',    'Hyderabad'),
(7,  'Tech recruiter at Google, building world-class teams.',        'MBA HR, XLRI (2018)',                     '6 years in talent acquisition',                 NULL,                           'https://linkedin.com/in/kiran',     NULL,                            'Bangalore'),
(8,  'Campus recruiter at Amazon, love finding fresh talent.',       'MBA HR, TISS Mumbai (2019)',              '5 years recruiting for tech roles',             NULL,                           'https://linkedin.com/in/meera',     NULL,                            'Chennai'),
(9,  'DevOps Engineer at Amazon, cloud infrastructure expert.',      'B.Tech IT, VIT (2020)',                   '4 years at Amazon, AWS DevOps team',            'https://resume.io/arjun',     'https://linkedin.com/in/arjun',     'https://github.com/arjun',     'Chennai'),
(10, 'Aspiring frontend developer, React enthusiast.',              'B.Tech CSE, SRM University (2025)',       'Intern at TCS (Winter 2024)',                   'https://resume.io/divya',     'https://linkedin.com/in/divya',     'https://github.com/divya',     'Chennai');

-- ============================================
-- 4. User_Skills
-- ============================================
-- Aarav (Student): JavaScript, React, Node.js, HTML/CSS, Git
INSERT INTO user_skills (user_id, skill_id) VALUES (1, 1), (1, 4), (1, 5), (1, 7), (1, 12);

-- Priya (Student): Python, Machine Learning, Data Analysis, SQL
INSERT INTO user_skills (user_id, skill_id) VALUES (2, 2), (2, 13), (2, 14), (2, 6);

-- Rahul (Alumni): JavaScript, Node.js, React, TypeScript, MongoDB, REST APIs
INSERT INTO user_skills (user_id, skill_id) VALUES (3, 1), (3, 5), (3, 4), (3, 8), (3, 11), (3, 15);

-- Sneha (Alumni): Data Analysis, Python, SQL
INSERT INTO user_skills (user_id, skill_id) VALUES (4, 14), (4, 2), (4, 6);

-- Vikram (Employee @Google): Java, Python, AWS, Docker, Kubernetes, Go
INSERT INTO user_skills (user_id, skill_id) VALUES (5, 3), (5, 2), (5, 9), (5, 10), (5, 17), (5, 19);

-- Ananya (Employee @Microsoft): C++, Python, Docker, Kubernetes, AWS
INSERT INTO user_skills (user_id, skill_id) VALUES (6, 16), (6, 2), (6, 10), (6, 17), (6, 9);

-- Arjun (Employee @Amazon): AWS, Docker, Kubernetes, Python, Go
INSERT INTO user_skills (user_id, skill_id) VALUES (9, 9), (9, 10), (9, 17), (9, 2), (9, 19);

-- Divya (Student): JavaScript, React, HTML/CSS, Figma, TypeScript
INSERT INTO user_skills (user_id, skill_id) VALUES (10, 1), (10, 4), (10, 7), (10, 20), (10, 8);

-- ============================================
-- 5. Jobs
-- ============================================
INSERT INTO jobs (recruiter_id, company_name, title, description, location, salary, deadline) VALUES
(7, 'Google',    'Software Engineer - L3',       'Join Google Cloud Platform team. Build scalable distributed systems. Work with a world-class engineering team on products used by millions.', 'Bangalore', 2500000.00, '2026-08-15'),
(7, 'Google',    'Data Scientist',               'Apply ML models to improve search quality. Analyze large datasets and build predictive models. PhD or Masters preferred.', 'Hyderabad', 2800000.00, '2026-07-30'),
(8, 'Amazon',    'SDE-1 (Frontend)',             'Build delightful customer experiences for Amazon.in. Work with React, TypeScript, and AWS. Fast-paced environment.', 'Chennai', 1800000.00, '2026-09-01'),
(8, 'Amazon',    'DevOps Engineer',              'Manage CI/CD pipelines and cloud infrastructure at scale. Experience with AWS, Docker, and Kubernetes required.', 'Hyderabad', 2200000.00, '2026-08-20'),
(7, 'Microsoft', 'Backend Engineer - Azure',     'Build Azure cloud services. Strong C++ or Java fundamentals required. Work on high-scale distributed systems.', 'Bangalore', 2400000.00, '2026-07-31');

-- ============================================
-- 6. Job_Skills
-- ============================================
-- Google SDE (job 1): Java, Python, AWS, Docker
INSERT INTO job_skills (job_id, skill_id) VALUES (1, 3), (1, 2), (1, 9), (1, 10);

-- Google Data Scientist (job 2): Python, Machine Learning, Data Analysis, SQL
INSERT INTO job_skills (job_id, skill_id) VALUES (2, 2), (2, 13), (2, 14), (2, 6);

-- Amazon SDE Frontend (job 3): JavaScript, React, TypeScript, HTML/CSS
INSERT INTO job_skills (job_id, skill_id) VALUES (3, 1), (3, 4), (3, 8), (3, 7);

-- Amazon DevOps (job 4): AWS, Docker, Kubernetes, Python
INSERT INTO job_skills (job_id, skill_id) VALUES (4, 9), (4, 10), (4, 17), (4, 2);

-- Microsoft Backend (job 5): C++, Java, Docker, Kubernetes
INSERT INTO job_skills (job_id, skill_id) VALUES (5, 16), (5, 3), (5, 10), (5, 17);

-- ============================================
-- 7. Connections (12 connections across users)
-- ============================================
INSERT INTO connections (sender_id, receiver_id, status) VALUES
(1, 5, 'accepted'),    -- Aarav → Vikram (Google)
(1, 3, 'accepted'),    -- Aarav → Rahul (Alumni)
(1, 6, 'pending'),     -- Aarav → Ananya (Microsoft) - pending
(2, 4, 'accepted'),    -- Priya → Sneha (Alumni)
(2, 5, 'accepted'),    -- Priya → Vikram (Google)
(2, 9, 'pending'),     -- Priya → Arjun (Amazon) - pending
(3, 5, 'accepted'),    -- Rahul → Vikram (Google)
(3, 6, 'accepted'),    -- Rahul → Ananya (Microsoft)
(10, 3, 'accepted'),   -- Divya → Rahul (Alumni)
(10, 9, 'accepted'),   -- Divya → Arjun (Amazon)
(10, 5, 'pending'),    -- Divya → Vikram (Google) - pending
(4, 6, 'accepted');    -- Sneha → Ananya (Microsoft)

-- ============================================
-- 8. Referral Requests
-- ============================================
INSERT INTO referral_requests (applicant_id, referrer_id, job_id, status, message) VALUES
(1, 5, 1, 'accepted',  'Hi Vikram, I am very interested in the Google SDE role. I have strong experience with Java and distributed systems from my projects. Would you be able to refer me?'),
(2, 5, 2, 'pending',   'Hello Vikram, I am a final-year ML student and the Data Scientist role at Google is my dream job. I would really appreciate a referral.'),
(1, 3, 3, 'pending',   'Hi Rahul, I noticed an SDE Frontend role at Amazon. Could you help me with a referral? I have strong React experience.'),
(10, 9, 3, 'accepted', 'Hi Arjun, the Amazon Frontend SDE role looks perfect for me. I have been working with React and TypeScript extensively. Would love a referral!'),
(2, 4, 2, 'rejected',  'Hi Sneha, could you refer me for the Google Data Scientist position? I have relevant ML experience.');

-- ============================================
-- 9. Applications
-- ============================================
INSERT INTO applications (applicant_id, job_id, status) VALUES
(1, 1, 'referred'),              -- Aarav applied to Google SDE → referred by Vikram
(1, 3, 'applied'),               -- Aarav applied to Amazon Frontend → waiting
(2, 2, 'applied'),               -- Priya applied to Google DS
(2, 4, 'applied'),               -- Priya applied to Amazon DevOps
(10, 3, 'referred'),             -- Divya applied to Amazon Frontend → referred by Arjun
(3, 5, 'interview_scheduled'),   -- Rahul applied to Microsoft Backend → interview
(10, 1, 'applied'),              -- Divya applied to Google SDE
(1, 5, 'rejected');              -- Aarav applied to Microsoft Backend → rejected
